# This is the main configuration file. Change values below
## Essential information
swmmResultCodes: ['NODE', 'J3', 0] # 0 - depth of water above invert see https://pypi.python.org/pypi/SWMM5

cdfs: # make sure that there are enough cdfs to match the number of variables slots in the template file. 
- cdf1.dat
- cdf2.dat

templatefile: "template.inp_" # template file name, swmm input file with each slot indicated as @!xx!@. xx can be an expression too. 
# xx should be an expression with v1..v<cdfs>) (n is the number of CDFs). 
# e.g. if there are two cdfs, then variables v1 and v2 are available to be used. 
# See https://www.simple-is-better.org/template/pyratemp.html#overview for information.  

nruns: 200 # how many runs to be simulated. Please make sure that this number is a multiple of num_cpus*quequesize 
# if not, the actual number of runs may be a bit less than nruns! (no harm done!)

## Performance related information 
num_cpus: 4  # Number of processor cores you have is a good estimate for this (e.g. 4 for typical laptops). 
# keep this at num_cpus: 1 for debugging (no multithreading then)
queuesize: 5 # How many simulations are fed into each process in the process pool 

## Other information 
datadirectory: "../data" # directory with data (this is where template file should be)
tmpdirectory: "../tmp"   # temporary storage. 
outputfile: "../run/outputx.dat"
plotcmd: ["python", "../src/plotcdf.py"] # command to run the plotter. 
## optional inforamation 
# seed: 5 # set the seed to get repeatable results during testing. 
#For real runs, its better to comment this (so that each time the programe starts with a different random seed)
dist_names: ['beta', 'norm',] # https://docs.scipy.org/doc/scipy/reference/stats.html#continuous-distributions for possible values. 
